baseURL = "http://blog.mingky.me"
title = "MINGKYME"
theme = "hugo-coder"
languageCode = "kr"
defaultContentLanguage = "kr"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
avatarURL = "images/avatar.jpg"

[params]
author = "MINGKYME"
description = "MINGKYME의 메모장"
keywords = "blog,developer,personal"
info = ["Go Developer"]
dateFormat = "January 2, 2006"
since = 2022
colorScheme = "auto"
maxSeeAlsoItems = 5

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/mingkyme/"

[[languages.kr.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.kr.menu.main]]
name = "Post"
weight = 2
url = "posts/"
